import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class NewCustomerForm extends javax.swing.JFrame {
    
    Connection con ;
   
    
   

    public NewCustomerForm() {
        initComponents();
       
      try {
          con = DriverManager.getConnection("jdbc:derby://localhost:1527/HotelManagementSystem", "jon", "111319");
          
      } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null,"Database not connected","Error",JOptionPane.ERROR_MESSAGE);
      }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        PhoneNumber = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        PresentAddress = new javax.swing.JTextField();
        PermanentAddress = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        NumberofChildren = new javax.swing.JTextField();
        NumberofAdults = new javax.swing.JTextField();
        TotalResidant = new javax.swing.JTextField();
        Register = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        RoomType = new javax.swing.JComboBox<>();
        BedType = new javax.swing.JComboBox<>();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        CalculateTotalCost = new javax.swing.JButton();
        txt4 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        CheckOutDate = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        CheckInDate = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt5 = new javax.swing.JTextField();
        ShowAvailableRooms = new javax.swing.JButton();
        txt6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Name :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 54, 153, 35));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Phone Number :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 110, 153, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Email :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 172, 153, 35));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Present Address :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 230, -1, 35));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Permanent Address :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 288, -1, 35));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Age :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 410, 153, 35));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Number of Children :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 477, -1, 35));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Number of Adults :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 532, 181, 35));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Total Residant :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 153, 35));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Room type :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 170, 35));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Bed type :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 153, 35));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Serial number of Room :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 600, 262, 47));

        Name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 49, 462, 40));

        PhoneNumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberActionPerformed(evt);
            }
        });
        getContentPane().add(PhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 107, 462, 46));

        Email.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 169, 462, 47));

        PresentAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(PresentAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 227, 462, 47));

        PermanentAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(PermanentAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 288, 462, 41));

        Age.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 398, 462, 47));

        NumberofChildren.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(NumberofChildren, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 466, 462, 46));

        NumberofAdults.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(NumberofAdults, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 530, 462, 44));

        TotalResidant.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(TotalResidant, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 462, 46));

        Register.setBackground(new java.awt.Color(255, 255, 255));
        Register.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Register.setText("Register");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        getContentPane().add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 710, 181, 68));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 710, 181, 68));

        RoomType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "AC(per day 2000 BDT)", "Non AC(per day 1000 BDT)" }));
        RoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomTypeActionPerformed(evt);
            }
        });
        getContentPane().add(RoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 60, -1, 35));

        BedType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BedType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Single(1000)", "Double(1500)" }));
        BedType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BedTypeActionPerformed(evt);
            }
        });
        getContentPane().add(BedType, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 130, 273, 35));

        txt2.setEditable(false);
        txt2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 60, 278, 35));

        txt3.setEditable(false);
        txt3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 130, 278, 35));

        CalculateTotalCost.setBackground(new java.awt.Color(255, 255, 255));
        CalculateTotalCost.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CalculateTotalCost.setText("Calculate Total Cost");
        CalculateTotalCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateTotalCostActionPerformed(evt);
            }
        });
        getContentPane().add(CalculateTotalCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 410, -1, 49));

        txt4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 400, 256, 49));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Check in Date:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 268, 224, 46));
        getContentPane().add(CheckOutDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1011, 330, 257, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Check out Date :");
        jLabel16.setToolTipText("");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 330, 183, 37));

        CheckInDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInDateActionPerformed(evt);
            }
        });
        getContentPane().add(CheckInDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1011, 272, 257, 42));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Total number of Days :");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 213, 222, 42));

        txt5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt5ActionPerformed(evt);
            }
        });
        getContentPane().add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1009, 213, 259, 42));

        ShowAvailableRooms.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ShowAvailableRooms.setText("Show Available Rooms");
        ShowAvailableRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAvailableRoomsActionPerformed(evt);
            }
        });
        getContentPane().add(ShowAvailableRooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 500, 270, 70));

        txt6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 600, 210, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CommonBackground.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void RoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomTypeActionPerformed
        // TODO add your handling code here:
        String Roomtype;
        Roomtype = (String)RoomType.getSelectedItem();
        txt2.setText(Roomtype);
    }//GEN-LAST:event_RoomTypeActionPerformed

    private void BedTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BedTypeActionPerformed
        // TODO add your handling code here:
        String Bedtype;
        Bedtype = (String)BedType.getSelectedItem();
        txt3.setText(Bedtype);
    }//GEN-LAST:event_BedTypeActionPerformed

    private void CalculateTotalCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateTotalCostActionPerformed
        // TODO add your handling code here:
        double TotalCost;
        
        String Roomtype;
        Roomtype = (String)RoomType.getSelectedItem();
        String Bedtype;
        Bedtype = (String)BedType.getSelectedItem();
        Double Days;
        Days = Double.parseDouble(txt5.getText());
        if("AC(per day 2000 BDT)".equals(Roomtype) && "Single(1000)".equals(Bedtype)){
          TotalCost=(2000+1000)*Days; 
          txt4.setText(String.valueOf(TotalCost));
        }
        
        if("AC(per day 2000 BDT)".equals(Roomtype) && "Double(1500)".equals(Bedtype)){
          TotalCost=(2000+1500)*Days; 
          txt4.setText(String.valueOf(TotalCost));
        }
        
        
        if("Non AC(per day 1000 BDT)".equals(Roomtype) && "Single(1000)".equals(Bedtype)){
          TotalCost=(1000+1000)*Days; 
          txt4.setText(String.valueOf(TotalCost));
        }
        
        if("Non AC(per day 1000 BDT)".equals(Roomtype) && "Double(1500)".equals(Bedtype)){
          TotalCost=(1000+1500)*Days; 
          txt4.setText(String.valueOf(TotalCost));
        }
        
        
    }//GEN-LAST:event_CalculateTotalCostActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt5ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt5ActionPerformed

    private void CheckInDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInDateActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_CheckInDateActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_NameActionPerformed

    private void PhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PhoneNumberActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        // TODO add your handling code here:
        String CusName = Name.getText();
        String phoneNumber = PhoneNumber.getText();
        String email = Email.getText();
        String preAdd = PresentAddress.getText();
        String permAdd =PermanentAddress.getText();
        String age = Age.getText();
        String numofChildren = NumberofChildren.getText();
        String numofAdults = NumberofAdults.getText();
        String totalResidants = TotalResidant.getText();
        String checkinDate = CheckInDate.getText();
        String checkoutDate = CheckOutDate.getText();
        String totalDays =  txt5.getText();
        String roomType = txt2.getText();
        String bedType = txt3.getText();
        String totalCost = txt4.getText();
        String serialNumberofRoom = txt6.getText();
        String Confirmation = "Not Confirmed";
        
       
        
        String query1 = "INSERT INTO PENDINGCUSTOMER (\"NAME\", PHONENUMBER,EMAIL,PRESENTADDRESS,PERMANENTADDRESS,AGE,NUMBEROFCHILDREN,NUMBEROFADULTS,TOTALRESIDANTS,ROOMTYPE,BEDTYPE,TOTALNUMBEROFDAYS,CHECKINDATE,CHECKOUTDATE,TOTALCOST,SERIALNUMBEROFROOM,CONFIRMATION) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        try {
            PreparedStatement ps = con.prepareStatement(query1);
            ps.setString(1, CusName);
            ps.setString(2, phoneNumber);
            ps.setString(3, email);
            ps.setString(4, preAdd); 
            ps.setString(5, permAdd);
            ps.setString(6, age);
            ps.setString(7, numofChildren);
            ps.setString(8, numofAdults);
            ps.setString(9, totalResidants);
            ps.setString(10,roomType);
            ps.setString(11,bedType);
            ps.setString(12,totalDays);
            ps.setString(13,checkinDate);
            ps.setString(14,checkoutDate);
            ps.setString(15,totalCost);
            ps.setString(16,serialNumberofRoom);
            ps.setString(17,Confirmation);
        
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(NewCustomerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RegisterActionPerformed

    private void ShowAvailableRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAvailableRoomsActionPerformed
        // TODO add your handling code here:
        new ShowRooms().setVisible(true);
    }//GEN-LAST:event_ShowAvailableRoomsActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewCustomerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age;
    private javax.swing.JComboBox<String> BedType;
    private javax.swing.JButton CalculateTotalCost;
    private javax.swing.JTextField CheckInDate;
    private javax.swing.JTextField CheckOutDate;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField NumberofAdults;
    private javax.swing.JTextField NumberofChildren;
    private javax.swing.JTextField PermanentAddress;
    private javax.swing.JTextField PhoneNumber;
    private javax.swing.JTextField PresentAddress;
    private javax.swing.JButton Register;
    private javax.swing.JComboBox<String> RoomType;
    private javax.swing.JButton ShowAvailableRooms;
    private javax.swing.JTextField TotalResidant;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    // End of variables declaration//GEN-END:variables
}
