/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jotir
 */
public class Reception extends javax.swing.JFrame {

    /**
     * Creates new form Reception
     */
    public Reception() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewCustomer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Review = new javax.swing.JButton();
        ConfirmedCustomer = new javax.swing.JButton();
        Bill = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NewCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewCustomerFormIcon.png"))); // NOI18N
        NewCustomer.setMaximumSize(new java.awt.Dimension(175, 155));
        NewCustomer.setMinimumSize(new java.awt.Dimension(175, 155));
        NewCustomer.setPreferredSize(new java.awt.Dimension(175, 155));
        NewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(NewCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 24, 161, 172));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("New Customer Form");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 81, 298, 53));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Write A Review");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 282, 227, 53));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Confirmed Customer");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 461, 262, 57));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Bill");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 622, 248, 63));

        Review.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Review.jpg"))); // NOI18N
        Review.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewActionPerformed(evt);
            }
        });
        getContentPane().add(Review, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 214, 161, 165));

        ConfirmedCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ConfirmedCustomer.png"))); // NOI18N
        ConfirmedCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmedCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmedCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 401, 161, -1));

        Bill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bill.png"))); // NOI18N
        getContentPane().add(Bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 591, 161, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 720, 173, 71));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reception.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 800));
        jLabel5.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCustomerActionPerformed
        // TODO add your handling code here:
        new NewCustomerForm().setVisible(true);
    }//GEN-LAST:event_NewCustomerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new SelectionPage().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ConfirmedCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmedCustomerActionPerformed
        // TODO add your handling code here:
        new ConfirmedCustomer().setVisible(true);
    }//GEN-LAST:event_ConfirmedCustomerActionPerformed

    private void ReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new WriteAReview().setVisible(true);
    }//GEN-LAST:event_ReviewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reception().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bill;
    private javax.swing.JButton ConfirmedCustomer;
    private javax.swing.JButton NewCustomer;
    private javax.swing.JButton Review;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
